name: Running Lab test with custom bash script

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up gcc
        run: sudo apt-get install gcc
      - name: Set up jq
        run: sudo apt-get install jq
      - name: Set up ninja
        run: sudo apt-get install ninja-build
      - name: Grant execute permission for testing script
        run: chmod +x launch_test.sh
      - name: Start tests
        run: ./launch_test.sh